### ISSUE TITLE
Fix semantics in profile rocrate-metadata.json

### ISSUE THREAD

**Issue by cedricdcc** [emo-bon/observatory-profile#1]
extend the @context in rocrate-metadata.json to include the semantic references for terms [crateRepo,sembenchConfig](https://open-vocabularies.vliz.be/dmbonassistant).

Add these term also to the [ontology](https://open-vocabularies.vliz.be/dmbonassistant)

**Comment by cpavloud** [comment]
Tagging @kmexter to keep an eye

**Comment by cedricdcc** [comment]
@kmexter The links provided in the initial comment for this issue are depricated. The emobon ontologies and vocabs are avialable at https://data.emobon.embrc.eu/ns/ .

The problem I have now is these vocabs are specifcally made for handling the classes and datatype properties in the data that is generated by @bulricht action. these involve the data from the triples files themselves and not the metadata that describes the file in the rocrate thus I don't think that this is an issue anymore.

**Comment by kmexter** [comment]
Urm....do you need me to look at something or not? If not, then go ahead and do whatever you think should be done.
