### ISSUE TITLE
Pigments / Phaeopigments definitions and examples

### ISSUE THREAD

**Issue by cpavloud** [emo-bon/observatory-profile#10]
@09012000-tosca 
In the [sediment google spreadsheeets](https://drive.google.com/drive/folders/1nhBmpHIJ60k30shRkKq5p9uyBWGpZouk) and in the [water google spreadsheets](https://drive.google.com/drive/folders/1kJXi46_8TydJuxb8Ltbd5eLOW1aUKIc3)

For pigments, pigments_method, phaeopigments, phaeopigments_method 
the definitions and examples will have to change. 
**Pigments**: it says "Concentration of pigments other than chlorophyll-a; can include multiple pigments" but we have agreed that it will now just be one value put in there, so that definition will have to change.
I also see that the text in column D is wrong - it has copied from phaeopigments by mistake. I guess the text should now be "pigment name measurement value in microgram per liter (ug/l)"
The example I guess should now be just one value

**Pigment_method**: the definition should probably now be "Name of the type of pigment that was measured, and the method for the measurement of the concentration of pigments. Provide as much information as possible. If there is a relevant reference or SOP, provide doi or link"

And the same type of changes for **phaeopigments** (this is an ENA optional column, **pigments** will be a custom column)

**Comment by 09012000-tosca** [comment]
Pigment http://vocab.nerc.ac.uk/collection/C67/current/PIGX/

Phaeopigments definition in general
http://vocab.nerc.ac.uk/collection/S27/current/CS002902/

Phaeopigments in water http://vocab.nerc.ac.uk/collection/P09/current/PHTF/
Phaeopigments in sediments http://vocab.nerc.ac.uk/collection/P09/current/PHAS/

**Comment by cpavloud** [comment]
Tagging also @kmexter to keep an eye.

**Comment by 09012000-tosca** [comment]
@cpavloud regarding the methodologies more acetone, ethanol or methanol extraction?

**Comment by cpavloud** [comment]
The most common (and traditional) one is the acetone extraction of chlorophyll pigments.

**Comment by kmexter** [comment]
OK, so I have updated the logsheet_schema_extended file with the vocab terms. methodologies is not something that is necessary here. but the definitions in the definitions tab of all logsheets still need changing, so putting this issue on EMOBON HQ

**Comment by kmexter** [comment]
this issue is done now - any other decisions on pigements should be raised as a new issue
