### ISSUE TITLE
Make the Plenzia observatory Google sampling sheets public

### ISSUE THREAD

**Issue by cymon** [emo-bon/observatory-profile#17]
Google Sheets from Observatory "Plenzia" are currently not public  but have URLs in the observatory profiles.

**Comment by kmexter** [comment]
Do you guys at HCMR have the permissions to do that?

**Comment by kmexter** [comment]
They appear to be open to the correct public - is this still an issue, @cymon ?
none of the logsheets are open to everyone, only to named people. Perhaps the plentzia one needs someone else added? Who?

**Comment by cymon** [comment]
> They appear to be open to the correct public - is this still an issue, @cymon ? none of the logsheets are open to everyone, only to named people. Perhaps the plentzia one needs someone else added? Who?

The Google Sheets for Plentzia are the only ones I cannot download or view in a browser.

**Comment by kmexter** [comment]
which URLs? I will look to see if the permissions are wrong

**Comment by cymon** [comment]
The Plenzia logsheet URLs in [emo-bon/governance/logsheets.csv](https://raw.githubusercontent.com/emo-bon/governance-data/refs/heads/main/logsheets.csv) were previously (back in early August) saying they were not public. I just tried it again and they are saying [You need access. Request access, or switch to an account with access. ](
https://docs.google.com/spreadsheets/d/13XeETquTvY6F_8Re25E0BAmSxLi0mThDUXYay3Eb5-o/edit?usp=sharing) so I'll request access now... should be sorted...
