### ISSUE TITLE
add new column to logsheets

### ISSUE THREAD

**Issue by kmexter** [emo-bon/observatory-profile#22]
We want a new column in the sampling tab, it can go next to the tidal_stage column, for the water and sediment logsheets

- The name of the column should be noteworthy_env_cond
- The description for the definitions tab should be "If there were any noteworthy/special environmental conditions during the event, please note down the most appropriate term from the Environmental Ontology. This is so we can take this into account when analysing the samples/data. Some suggestions for terms are: "marine algal bloom [ENVO:02500036], coral bleaching process [ENVO:01000852], glacial abrasion [ENVO:01000682], storm [ENVO:01000876], drought [ENVO:1000745], rain [ENVO:01001564], snow [ENVO:01000406], hail [ENVO:03400011], oil spill [ENVO:00002061], increased temperature [PATO:0001305], environmental pollution [ENVO:02500036], biofouling [ENVO:06105023]"
- An example would be "marine algal bloom [ENVO:02500036]"
- It should be optional

Then we need to go over all logsheets to see if any terms could be added for events where there has been a comment made about such an event.

I think HCMR can do this once they have completed all the other corrections, it is not so urgent that it needs to be done asap

**Comment by melinalou** [comment]
Column added, definitions updated!

"Then we need to go over all logsheets to see if any terms could be added for events where there has been a comment made about such an event." -> not done

**Comment by kmexter** [comment]
@melinalou there is a mistake in the way this new column was created - it includes a drop-down menu that is taken from the tidal stage column (at least for BPNS sediment I saw this). You need to remove that.

**Comment by kmexter** [comment]
@laurianvm I have added this new term in the logsheet_schema file uploaded just now. We can discuss together with some other things

**Comment by kmexter** [comment]
checked with Bram - no affect on the harvest-QC action

**Comment by kmexter** [comment]
Just need @melanthia or @melinalou to fix the formatting mistake with the column (see a few comments above) and this issue can be closed

**Comment by melinalou** [comment]
done

**Comment by kmexter** [comment]
grand. Will we want to look at the logsheets to see if we can add info here based on comments or will we email the stations to ask them to add this info - I am sure some stations have talked about blooms affecting their sampling work

**Comment by cpavloud** [comment]
I think it's better that the stations added this themselves.

**Comment by kmexter** [comment]
me too - since we have to email them all about updates to the logsheets (see my suggestions on https://docs.google.com/document/d/1B1ZuuqN2rxDZZjpftpfHpvPVQ9cGUmpxlVdrdy4ccEk/edit?tab=t.0, "Frequently made errors" and "Summary of changes made to the logsheets, and particular reminders") we can make this request at the same time
@melanthia for you to send out, I think.
