### ISSUE TITLE
ARMS blanks

### ISSUE THREAD

**Issue by kmexter** [emo-bon/observatory-profile#24]
We are starting to get blanks from the ARMS units but I am not sure that the ARMS people fully understand how the blanks should be done in emo bon 
So (1) I think a reminder of how this should be done is timely (Matthias/Christina email?)
And (2) we need to decide what do do with the blank we have currently in the ARMS googlesheet https://docs.google.com/spreadsheets/d/1j3yuY5lmoPMo91w6e3kkJ6pmp1X6FVGUtLealuKJ3wE/edit?gid=855411053#gid=855411053 (which will need to be added to the ARMS-EMOBON logsheets later) 

We have only 3 blanks that have been processed into dna so far: two that that are associated with a unit but not with a fraction or filter size, and one that is not associated with even a unit. 
So, the original sample IDs are
EMOBON_Koster_VH1_Ha_210608_220608_(blank) -> associated with a unit, but not a fraction or filter
EMOBON_Koster_VH3_Ha_210608_220609_(blank) -> ditto
EMO BON PiEGetxo Ha 210729-211124 Blank -> just associated with an event date

Apparently the first two are correct, in that a blank is taken when a unit is processed but I think the fraction and filter are not part of this process. But the second is not correct (note that there are 2 arms units for this particular event).
I want to ask
1) Are we OK with this blank naming convention being EMOBON_Observatory_Unit_Ha_date_date_blank (i.e. no fraction and no filter size). I assume yes as someone would have made this decision, but I want to check
2) What should we do with the Getxo blank - either randomly assign it to one of the units, or double it and assign it to two units (which is incorrect as there was just one sample, but on the other hand the DNA from that could be assigned to both units if we assume they were processed at the same time in the lab). (FYI Justine wil ask Getxo if they remember what they did on that day but it was quite some time ago).

But we also have

**Comment by cpavloud** [comment]
It is logical and reasonable not to associate the ARMS blanks with fractions and filter sizes.

Also, it is logical to find blanks associated to an event and not a unit. 
E.g. if someone processes two ARMS units in one day, they will collect only one blank sample at the end of the processing. So, in this case this blank sample should be associated to both the units that were processed during that day. 
If there was only one ARMS unit being processed that day, then the blank should be assigned to that particular unit.

**Comment by cpavloud** [comment]
I don't think we need to remind them really, it is described in the Handbook. So, as long as they go through the Handbook, then it should be ok.

**Comment by JustinePa** [comment]
I just got confirmation from Getxo that their blank sample was for both G1 and G2, which are replicates of the same site with some meters of distance among them, from which samples were processed on the same day in the same lab and by the same people.
In only 3 blanks, we already see some divergence in methods... So we might have to give a quick reminder.

**Comment by cpavloud** [comment]
I think if we provide an example in the Handbook, we should be ok. 
Because it might be confusing, since we were not doing blanks before.

**Comment by kmexter** [comment]
indeed...but I still need to know what to do with the getxo (single) blank (for two units)....

**Comment by cpavloud** [comment]
I don't have any strong opinion and I don't know which is the best choice (data management wise). 

However I think that since the blank sample will have sequences (at least a few), then it might better if it is linked to all the units processed in a day and not in the event?
So, in other words, I would double the blank so each unit is associated with the blank sample.

**Comment by kmexter** [comment]
ok, that is what we will do - have added a new row to the ARMS overview GS to copy the Getxo blank to arms units G1 and G2
