### ISSUE TITLE
Adding ROR identifiers to the Observatory metadata sheets

### ISSUE THREAD

**Issue by cymon** [emo-bon/observatory-profile#30]
It would be good to identify the Organizations in our ro-crates by their [ROR ID as in this example here](https://www.researchobject.org/ro-crate/specification/1.1/contextual-entities.html#organizations-as-values).

Can we add the ROR ID to the Observatory sheets metadata in the Google logsheets?

The problem being, although ROR has an API, it works only when you know the ROR ID, and finding that via other information is not exact.

**Comment by cpavloud** [comment]
We have used the EDMO record Ids in the Observatory metadata. 
EDMO = [European Directory of Marine Organisations](https://edmo.seadatanet.org/)
Can this be used instead of the Research Organization Registry (ROR) id or we need to have both?

**Comment by cymon** [comment]
> We have used the EDMO record Ids in the Observatory metadata. EDMO = [European Directory of Marine Organisations](https://edmo.seadatanet.org/) Can this be used instead of the Research Organization Registry (ROR) id or we need to have both?

OK, they look good; in my opinion they would substitute for the ROR IDs - but maybe we should include both, I'm not sure but we need at least one. Where can I find the EDMO for the stations? Are they in any of the emo bon sheets?

**Comment by cymon** [comment]
Thanks! Going to use only that ID for the time being
