### ISSUE TITLE
BPNS has muliple organization_edmoid numbers

### ISSUE THREAD

**Issue by cymon** [emo-bon/observatory-profile#31]
It is possible for BPNS to choose one of the 4 different  organization_edmoid numbers presented?

We need to generate a single URL from this number.

[water_column/Observatory sheet](
https://docs.google.com/spreadsheets/d/1mEi4Bd2YR63WD0j54FQ6QkzcUw_As9Wilue9kaXO2DE/edit?gid=2052143695#gid=2052143695)

**Comment by kmexter** [comment]
unfortunately no, BPNS is a combination of all these institutes

**Comment by cymon** [comment]
Fair enough; the first one is going to get the link :)

**Comment by kmexter** [comment]
in what? we do need to acknowledge everyone? in the triple store all of them are carried thru, and they will also be in the observatory ro-crates. not sure they need to go in the mgf ro-crates.....

**Comment by cymon** [comment]
e.g:
```

        {
            "@id": "Flanders Marine Institute (VLIZ); Ghent University; Royal Belgian Institute of Natural Sciences; Katholieke Universiteit Leuven",
            "@type": "Organization",
            "name": "Flanders Marine Institute (VLIZ); Ghent University; Royal Belgian Institute of Natural Sciences; Katholieke Universiteit Leuven",
            "country": "Belgium",
            "identifier": "https://edmo.seadatanet.org/report/422; 449; 432; 2248"
        },
        {
            "@id": "Jonas Mortelmans",
            "@type": "Person",
            "name": "Jonas Mortelmans",
            "memberOf": "Flanders Marine Institute (VLIZ); Ghent University; Royal Belgian Institute of Natural Sciences; Katholieke Universiteit Leuven",
            "identifier": "https://orcid.org/0000-0002-8781-7915",
            "affiliation": "https://edmo.seadatanet.org/report/422; 449; 432; 2248"
        },
```

I could loop the ID's and make a list: but I was just hoping you could just choose one, rather than me having to make a special case for VLIZ.

**Comment by kmexter** [comment]
I mean in where - where are you putting this info? It will be in the observatory ro-crate.json file and I don't think it needs to be in the metagoflow ro-crate,json files -> if you just point to the sample id, ena number, and obervaotry ro-crate.json file for that sample, in your mgf ro-crat.json files, is that not enough?

**Comment by cymon** [comment]
https://github.com/emo-bon/metaGOflow-data-products-RO-crate-example/issues/4

**Comment by kmexter** [comment]
ok, well it does not matter so much there since the full acknowledgement is made in the observatory's own ro-crate
