### ISSUE TITLE
NRMBC_SZN: "ship_date" in soft_sediment is a string not date

### ISSUE THREAD

**Issue by cymon** [emo-bon/observatory-profile#35]
Processing observatory_id='NRMCB' - sampling_strategy='soft_sediment' - sheet_type='sampling'
[Sample sheet link:](https://docs.google.com/spreadsheets/d/1a19q3w2sP7dae8HEzT5TdmfqhRQQd3GItFqiYxWJlxs/gviz/tq?tqx=out:csv&sheet=sampling)

ship_date has "expected 09-2024" not ISO date format

**Comment by kmexter** [comment]
that is ok - when they write "Expected xxxx" it is simply to indicate to us that at some point a value will come, rather than a value will never come. in the transformed logsheets we make this will not get carried forward

**Comment by cymon** [comment]
Then we need to change the definition of that field.

**Comment by kmexter** [comment]
we need to add a general rule that "Expected xx-xx" is required if a value will come, or NA if not -> that can be added to the description tab. but all stations have also been told already. but the field itself, the formal definition, should not change.

**Comment by cymon** [comment]
OK, so in validation, anything that isnt an ISO date format is going to get ignored; everything downstream is N/A or None.

**Comment by cymon** [comment]
Closing
