### ISSUE TITLE
Bergen: sampling sheet has arr_hq_date field instead of arr_data_hq

### ISSUE THREAD

**Issue by cymon** [emo-bon/observatory-profile#39]
https://docs.google.com/spreadsheets/d/1HuXHiUJICZrmCrJ4EZDyU5aSCMzDAc1cy_tne5YVPTg/edit?gid=787674917#gid=787674917

sampling sheet has arr_hq_date field instead of arr_data_hq

**Comment by cpavloud** [comment]
This comment should have been created in the [dedicated repo for Bergen](https://github.com/emo-bon/observatory-bergen-crate).

Anyway, I have corrected the column name.
